% ========================================================================
% Plot effect of histology ROI size on effective radius sampling
% distribution, bias and precision.
% ========================================================================

% load data
r_bin_centers = readtable(fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/desc-binCenters_radii.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t");
r_bin_centers = r_bin_centers.Variables;
r_bin_edges = readtable(fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/desc-binEdges_radii.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t");
r_bin_edges = r_bin_edges.Variables;
r_bin_counts = readtable(fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/desc-countsCircularEq_radii.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t");
r_bin_counts = r_bin_counts.Variables;
sim_params = get_default_simulation_parameters();

% simulate r_eff sampling distributions
roi_sizes = round(logspace(2, 5, 7));
iterations_per_sample_size = 1000;
r_effs = zeros(size(r_bin_counts,1), ...
    length(roi_sizes), ...
    iterations_per_sample_size);
r_effs_ref = zeros(size(r_bin_counts,1), 1);
sample_sizes_ref = zeros(size(r_bin_counts,1), 1);
parfor roi_index = 1:size(r_bin_counts,1)
    rand_stream = RandStream(sim_params.random_generator, ...
        'Seed', sim_params.random_seed);
    RandStream.setGlobalStream(rand_stream);
    r_effs_ref(roi_index) = compute_r_eff_from_distribution(...
        'BinCenters', r_bin_centers, ...
        'BinCounts', r_bin_counts(roi_index,:)');
    sample_sizes_ref(roi_index) = sum(r_bin_counts(roi_index,:));
    section_radii = convert_bin_counts_to_set( ...
        r_bin_counts(roi_index,:), r_bin_centers);    
    r_effs_roi = zeros(length(roi_sizes), iterations_per_sample_size);
    for roi_size_index = 1:length(roi_sizes)
        for iteration_index = 1:iterations_per_sample_size
            axon_radii = datasample(rand_stream, ...
                section_radii, ...
                roi_sizes(roi_size_index), ...
                'Replace', false);
            r_effs_roi(roi_size_index, iteration_index) = ...
            compute_r_eff_from_distribution(axon_radii);
        end
    end
    r_effs(roi_index,:,:) = r_effs_roi;
end

% compute bias and precision (as cov) from r_eff sampling distributions
biases = zeros(length(roi_sizes), size(r_bin_counts,1));
covs = zeros(length(roi_sizes), size(r_bin_counts,1));
for roi_size_index = 1:length(roi_sizes)
    r_effs_per_sample_size = squeeze(r_effs(:,roi_size_index,:));
    biases(roi_size_index,:) = ...
        mean(100*(r_effs_per_sample_size-r_effs_ref)./r_effs_ref, 2);
    covs(roi_size_index,:) = ...
        std(100*(r_effs_per_sample_size-r_effs_ref)./r_effs_ref, [], 2);
end

% set up figure
fig_handle  = figure;
set(fig_handle, get_default_figure_settings());
set(gcf, ...
    'units', 'centimeters', ...
    'position', [0, 0, 12.6, 4.6]);
layout = tiledlayout(1, 3, ...
    'Padding', 'tight', ...
    'TileSpacing','tight');
plot_axes = gobjects(1, 3);
box_face_color = [1 1 1];
lm_color = [0, 0.47, 0.84];
color_order = get_default_color_order();
aboitiz_color = color_order(1,:);
caminiti_color = color_order(2,:);
sample_size_colors = [...
    box_face_color; 
    aboitiz_color; 
    box_face_color; 
    caminiti_color; 
    box_face_color; 
    box_face_color; 
    box_face_color];

% plot r_eff sampling distribution for example roi
example_section_index = 33;
plot_axes(1) = nexttile(layout);
hold on;
ylims = [0 5];
ylim(ylims);
plot(sample_sizes_ref(example_section_index), ...
    r_effs_ref(example_section_index),...
    'o', ...
    'Color', lm_color, ...
    'MarkerEdgeColor', [0 0 0],...
    'MarkerFaceColor', lm_color,...
    'MarkerSize', 5, ...
    'LineWidth', 1, ...
    'DisplayName', ...
    "Whole lsLM section");
xtick_vals = logspace(1, 8, 8);
xlims = minmax(xtick_vals);
plot(xlims, ...
    [r_effs_ref(example_section_index) ...
    r_effs_ref(example_section_index)], ...
    '--', ...
    'Color', lm_color, ...
    'HandleVisibility','off');
for roi_size_index = 1:length(roi_sizes)
    r_eff_values = ...
        squeeze(r_effs(example_section_index, roi_size_index, :));
    boxchart(repmat(roi_sizes(roi_size_index), ...
        length(r_eff_values), 1),...
        r_eff_values,...
        'BoxWidth', 1.5*round(roi_sizes(roi_size_index)/2),...
        'BoxFaceColor', sample_size_colors(roi_size_index,:),...
        'BoxFaceAlpha', 1,...
        'BoxEdgeColor', 'k',...
        'MarkerColor', 'k',...
        'MarkerStyle', '.',...
        'HandleVisibility','off');
end
set(gca, 'XScale', 'log');
xlim(xlims);
xlabel("axons per ROI", 'Interpreter', 'latex');
ylabel("$r_{\mathrm{eff}}~[\mu$m$]$", 'Interpreter', 'latex');
xticks(xtick_vals);
pbaspect([1 1 1]);
box on;

% plot bias versus roi size
plot_axes(2) = nexttile(layout);
hold on;
ylims = [-30 1];
ylim(ylims);
for roi_size_index = 1:length(roi_sizes)
    errorbar(roi_sizes(roi_size_index), ...
        mean(biases(roi_size_index,:)), ...
        std(biases(roi_size_index,:)), ...
        'o', ...
        'MarkerFaceColor',  sample_size_colors(roi_size_index,:), ...
        'MarkerEdgeColor', 'k',...
        'Color', 'k',...
        'MarkerSize', 5,...
        'LineWidth', 1);
end
xlabel("axons per ROI", 'Interpreter', 'latex');
ylabel("bias $[\%]$", 'Interpreter', 'latex');
set(gca, 'XScale', 'log');
xtick_vals = logspace(1, 6, 6);
xticks(xtick_vals);
xlim(minmax(xtick_vals));
pbaspect([1 1 1]);
box on;

% plot precision versus roi size
plot_axes(3) = nexttile(layout);
hold on;
ylims = [0 28];
ylim(ylims);
x = [0.5 4.5];
Y = repmat(max(ylim()), length(x), 1);
ylim(ylims);
for roi_size_index = 1:length(roi_sizes)
    errorbar(roi_sizes(roi_size_index), ...
    mean(covs(roi_size_index,:)), ...
    std(covs(roi_size_index,:)), ...
    'o', ...
    'MarkerFaceColor',  sample_size_colors(roi_size_index,:), ...
    'MarkerEdgeColor', 'k',...
    'Color', 'k',...
    'MarkerSize', 5,...
    'LineWidth', 1);
end
xlabel("axons per ROI", ...
    'Interpreter', 'latex');
label_h = ylabel("coef. of variation $[\%]$~~~", ...
    'Interpreter', 'latex');
set(gca, 'XScale', 'log');
xtick_vals = logspace(1, 6, 6);
xticks(xtick_vals);
xlim(minmax(xtick_vals));
pbaspect([1 1 1]);
box on;

% save figure
print(gcf, '-dsvg', "roi_size_impact.svg");