% ========================================================================
% Illustrate histological ROI locations.
% ========================================================================

% load data
roi_polygon_table = readtable( ...
    fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/desc-polygons_roicoords.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t", ...
    "TextType", "string");
roi_info_table = readtable( ...
    fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/roiinfo.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t", ...
    "TextType", "string");
subject_ids = unique(roi_info_table.subject_id);

% set up subplots
fig_handle  = figure;
set(fig_handle, get_default_figure_settings());
layout = tiledlayout(1, length(subject_ids));
layout.TileSpacing = "tight";
layout.Padding = "tight";
color_order = get_default_color_order();

%  plot rois as polygons
for subject_index = 1:length(subject_ids)
    sub_table = roi_info_table(...
        roi_info_table.subject_id == subject_ids(subject_index),:);

    % load corpus callosum image and mask 
    image_org_filename = ...
        fullfile(getenv("MRV_DATA_PATH"), ...
        "histology/rawdata", ...
        sprintf("sub-%s/sub-%s.png", ...
        subject_ids(subject_index), ...
        subject_ids(subject_index)));
    mask_org_filename = ...
        fullfile(getenv("MRV_DATA_PATH"), ...
        "histology/rawdata", ...
        sprintf("/sub-%s/sub-%s_label-cc_mask.png", ...
        subject_ids(subject_index), ...
        subject_ids(subject_index)));

    % apply corpus callosum mask to image
    image_org = imread(image_org_filename);
    mask_org = imread(mask_org_filename);
    mask = mean(mask_org,3) > 10;
    mask_rep = repmat(mask, 1, 1, size(image_org,3));
    image = uint8(255.*ones(size(image_org)));
    image(mask_rep>0) = image_org(mask_rep>0);

    % display corpus callosum image
    nexttile(layout);
    imagesc(image);
    axis image;
    title(sprintf("CC-%02d", subject_index));
    hold on;

    % annotate ROIs on corpus callosum image
    subject_roi_info_table = roi_info_table(... 
        roi_info_table.subject_id == subject_ids(subject_index),:);
    for roi_index = 1:height(subject_roi_info_table)  
        polygon_table_roi = roi_polygon_table(...
            roi_polygon_table.subject_id ...
            == subject_ids(subject_index) ...
            & roi_polygon_table.roi_id ...
            == subject_roi_info_table.roi_id(roi_index),:);
        polygon = [polygon_table_roi.x polygon_table_roi.y];
        h = drawpolygon('Position', polygon, ...
             'Color', color_order(subject_index,:), ...
            'MarkerSize', 0.000001, ...
            'FaceAlpha', 0.3);
        h.EdgeColor = "k";
    end
end

% save figure
print(gcf, '-dsvg', "histology_rois.svg");

