% ========================================================================
% Illustrate effect of Gaussian versus Rician noise on effective radius
% estimation, using the experimental in-vivo dMRI protocol
% ========================================================================

%% set up
roi_info_table = readtable(fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/roiinfo.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t", ...
    "TextType", "string");
sim_params = get_default_simulation_parameters();
sim_params.radius_approximation = "minor_axis";


%% ex-vivo dMRI simulations
% load parameters and precomputed signals per axon radius table
mr_protocol_ex_vivo = MrProtocol.fromJsonFile(...
    "../../../parameters/mr_protocol_ex_vivo_experimental.json");
tissue_params_ex_vivo = jsondecode(fileread( ...
    "../../../parameters/tissue_params_ex_vivo.json"));
signal_lut_ex_vivo = load(fullfile(getenv("MRV_DATA_PATH"), ...
    "simulations/signal_per_radius_ex_vivo_experimental.mat"));

% get histograms with ex-vivo tissue scaling
[r_roi_counts_ex_vivo, r_effs_reference_ex_vivo] = get_histology_data(...
    fullfile(getenv("MRV_DATA_PATH")),...
    sim_params.r_bin_edges,...
    sim_params.radius_approximation,...
    "scaling_factor", tissue_params_ex_vivo.histology_scaling_factor);

% get histograms with ex-vivo tissue scaling
[r_roi_counts_ex_vivo_circ_eq, r_effs_reference_ex_vivo_circ_eq] = get_histology_data(...
    fullfile(getenv("MRV_DATA_PATH")),...
    sim_params.r_bin_edges,...
    "circular_equivalent",...
    "scaling_factor", tissue_params_ex_vivo.histology_scaling_factor);

% get histograms with ex-vivo tissue scaling
[r_roi_counts_ex_vivo_minor_axis, r_effs_reference_ex_vivo_minor_axis] = get_histology_data(...
    fullfile(getenv("MRV_DATA_PATH")),...
    sim_params.r_bin_edges,...
    "minor_axis",...
    "scaling_factor", tissue_params_ex_vivo.histology_scaling_factor);

% get histograms with ex-vivo tissue scaling
[r_roi_counts_ex_vivo_major_axis, r_effs_reference_ex_vivo_major_axis] = get_histology_data(...
    fullfile(getenv("MRV_DATA_PATH")),...
    sim_params.r_bin_edges,...
    "major_axis",...
    "scaling_factor", tissue_params_ex_vivo.histology_scaling_factor);


%% plots
% set up figure
fig_handle  = figure;
set(fig_handle, get_default_figure_settings());
set(gcf,'units','centimeters','position',[0, 0, 12.1, 10.0]);
t = tiledlayout(1,2);
t.TileSpacing = "loose";
t.Padding = "tight";
color_order = get_default_color_order();
% color_ex_vivo = color_order(2,:);
% color_in_vivo = color_order(1,:);
legend_prefix_ex_vivo = "ex-vivo ";
legend_prefix_in_vivo = "in-vivo ";
lims = [0 7];

% plot circ. eq. comparison
ax_experiments = nexttile(t);
rand_stream = RandStream(sim_params.random_generator, ...
    'Seed', sim_params.random_seed);
plot_r_eff_correlation_ensemble(ax_experiments, ...
    r_effs_reference_ex_vivo_circ_eq, ...
    r_effs_reference_ex_vivo_minor_axis', ...
    'color', color_order(1,:), ...
    'xlim', lims, ...
    'ylim', lims, ...
    'rand_stream', rand_stream);
xlabel('$r_{\mathrm{eff}}$ [$\mu$m] (circular eq.)', ...
    'Interpreter', 'latex');
ylabel("$r_{\mathrm{eff}}$ [$\mu$m] (minor axis)", ...
    'Interpreter', 'latex');
lgd = legend('Interpreter', 'latex', ...
    'Location', 'northoutside', ...
    'FontSize', 7);
lgd.ItemTokenSize(1) = 10;

ax_experiments = nexttile(t);
rand_stream = RandStream(sim_params.random_generator, ...
    'Seed', sim_params.random_seed);
plot_r_eff_correlation_ensemble(ax_experiments, ...
    r_effs_reference_ex_vivo_circ_eq, ...
    r_effs_reference_ex_vivo_major_axis', ...
    'color', color_order(1,:), ...
    'xlim', lims, ...
    'ylim', lims, ...
    'rand_stream', rand_stream);
xlabel('$r_{\mathrm{eff}}$ [$\mu$m] (circular eq.)', ...
    'Interpreter', 'latex');
ylabel("$r_{\mathrm{eff}}$ [$\mu$m] (major axis)", ...
    'Interpreter', 'latex');
lgd = legend('Interpreter', 'latex', ...
    'Location', 'northoutside', ...
    'FontSize', 7);
lgd.ItemTokenSize(1) = 10;

% save_figure
print(gcf, '-dsvg', "radii_approx_comparison.svg");
