% ========================================================================
% Compute the mean SNR in the corpus callosum across ex-vivo MRI tissue 
% samples
% ========================================================================

% Experimental b-values (in s/mm²)
bvals = round(1000.0 .* ...
    [2.5; ...
    5.0; ...
    7.5; ...
    10.0; ...
    20.0; ...
    30.0; ...
    40.0; ...
    50.0; ...
    60.0; ...
    70.0; ...
    80.0; ...
    90.0; ...
    100.0]);

% Number of k-space repetitions per b-value
num_repetitions = [1; 1; 1; 1; 2; 2; 3; 3; 4; 5; 6; 7; 8];

% Processed data directory
processed_data_dir = fullfile(getenv("MRV_DATA_PATH"), ...
    "mri_ex_vivo/processed");
masks_dir = fullfile(getenv("MRV_DATA_PATH"), ...
    "mri_ex_vivo/masks");
processed_subject_dirs = dir(fullfile(processed_data_dir, "sub*"));
snr_values = zeros(length(processed_subject_dirs), ...
    length(num_repetitions));

for subject_id_index = 1:length(processed_subject_dirs)
    % Extract subject ID
    subject_id = sscanf( ...
        processed_subject_dirs(subject_id_index).name, 'sub-%s');

    % Find available noise maps
    noisemap_files = dir(fullfile( ...
        processed_subject_dirs(subject_id_index).folder, ...
        processed_subject_dirs(subject_id_index).name, ...
        sprintf("dwi/sub-%s_sample-*_noisemap.nii.gz", subject_id)));

    snr_values_subject = nan(length(noisemap_files), ...
        length(num_repetitions));

    for sample_index = 1:length(noisemap_files)

        % Load noise map per shell and corresponding b-values
        noisemap = niftiread(fullfile( ...
            processed_subject_dirs(subject_id_index).folder, ...
            processed_subject_dirs(subject_id_index).name, ...
            sprintf("dwi/sub-%s_sample-%02d_noisemap.nii.gz", ...
            subject_id, sample_index)));
        noisemap_bvals = readmatrix(fullfile( ...
            processed_subject_dirs(subject_id_index).folder, ...
            processed_subject_dirs(subject_id_index).name, ...
            sprintf("dwi/sub-%s_sample-%02d_noisemap.bval", ...
            subject_id, sample_index)), ...
            "FileType", "text");

        % Load tissue mask
        tissue_mask_file = fullfile(masks_dir, ...
            sprintf("sub-%s/dwi" + ...
            "/sub-%s_sample-%02d_label-tissue_mask.nii.gz", ...
            subject_id, subject_id, sample_index));
        tissue_mask = niftiread(tissue_mask_file);

        for bval_index = 1:length(bvals)
            % Check if current b-value exists in the noise map b-values
            [isPresent, idx] = ismember(bvals(bval_index), ...
                noisemap_bvals);            
            if isPresent
                noisemap_b = noisemap(:,:,:,idx);
                sigma_norm_values = noisemap_b(tissue_mask > 0);
                snr_values_subject(sample_index, bval_index) = ...
                    mean(1./sigma_norm_values, 'omitnan');
            end
        end
    end

    % Compute subject-level mean SNR per b-value
    snr_values(subject_id_index, :) = ...
        mean(snr_values_subject, 1, 'omitnan');
end

% Compute and display mean SNR across subjects
disp("Average SNR in the corpus callosum per b");
snr_values_per_b = mean(snr_values, 1, 'omitnan');
for b_index = 1:length(bvals)
    disp(['b = ', num2str(bvals(b_index)), ...
        ': SNR = ', num2str(snr_values_per_b(b_index), '%.1f')]);
end
