% ========================================================================
% Compute signals for discrete radii for experimental ex-vivo dMRI protocol
% ========================================================================

% set up parameters and protocol
sim_params = get_default_simulation_parameters();
tissue_params = jsondecode(fileread(...
    "../../parameters/tissue_params_ex_vivo.json"));
mr_protocol = MrProtocol.fromJsonFile(....
    "../../parameters/mr_protocol_ex_vivo_experimental.json");

% run simulations
signal_per_r = simulate_signals_single_axon( ...
    sim_params.r_bin_centers, ...
    mr_protocol, ...
    tissue_params, ...
    "signal_approximation", "matrix");

r_bin_centers = sim_params.r_bin_centers;
r_bin_edges = sim_params.r_bin_edges;
save(fullfile(getenv("MRV_DATA_PATH"),...
    "simulations/signal_per_radius_ex_vivo_experimental.mat"), ...
    "signal_per_r", ...
    "r_bin_centers", ...
    "r_bin_edges", ...
    "mr_protocol");
