% ========================================================================
% Compute the median SNR in the corpus callosum across in-vivo MRI subjects
% ========================================================================

cc_eval_params = jsondecode(fileread(...
    "../../parameters/cc_evaluation_parameters.json"));
processed_data_dir = fullfile(getenv("MRV_DATA_PATH"), ...
    "mri_in_vivo/processed");
processed_subject_data_dirs = dir(fullfile(processed_data_dir, "sub*"));
snr_values = zeros(1, length(processed_subject_data_dirs));

for subject_id_index = 1:length(processed_subject_data_dirs)

    % extract subject_id from folder name
    subject_id = sscanf(processed_subject_data_dirs( ...
        subject_id_index).name, 'sub-%s');
    
    % read images
    sigma_image = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_noisemap.nii.gz", ...
        subject_id, subject_id)));
    dwi_image = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_dwi.nii.gz", ...
        subject_id, subject_id)));
    dwi_bval = readmatrix(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_dwi.bval", ...
        subject_id, subject_id)), 'FileType', 'text');
    fa_image = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_FA.nii.gz", ...
        subject_id, subject_id)));
    effective_radius_image = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_effectiveRadius.nii.gz", ...
        subject_id, subject_id)));
    cc_atlas_mask = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/" + ...
        "sub-%s_label-ccMid_mask.nii.gz", ...
        subject_id, subject_id)));
    
    % compute SNR as S(b=0)/sigma;
    dwi_image_b0 = dwi_image(:,:,:,dwi_bval==0);
    dwi_image_b0_mean = mean(dwi_image_b0, 4);
    snr_image = dwi_image_b0_mean./sigma_image;

    % generate corpus callosum mask
    cc_mask = cc_atlas_mask > 0 ...
        & fa_image >= cc_eval_params.fa_min ...
        & effective_radius_image >= cc_eval_params.r_eff_min;
    
    % compute mean SNR in the corpus callosum
    snr_values(subject_id_index) = mean( ...
        snr_image(cc_mask), 'omitnan');

end

disp(['Median SNR in the corpus callosum ', ...
    num2str(median(snr_values, 'omitnan'), '%.1f')]);
