% ========================================================================
% Compute signals for discrete radii for experimental ex-vivo dMRI protocol
% for various immobile water fraction values.
% ========================================================================

% set up parameters and protocol
sim_params = get_default_simulation_parameters();
tissue_params = jsondecode(fileread(...
    "../../../parameters/tissue_params_ex_vivo.json"));
mr_protocol = MrProtocol.fromJsonFile(....
    "../../../parameters/mr_protocol_ex_vivo_experimental.json");

f_im_step = 0.005;
f_im_bin_centers = 0:f_im_step:tissue_params.f_im*2.5;
f_im_bin_edges = [f_im_bin_centers - f_im_step/2, f_im_bin_centers(end) + f_im_step/2];

signal_per_r = zeros(length(f_im_bin_centers), ...
     sum(mr_protocol.num_gradient_directions_per_shell), ...
     length(sim_params.r_bin_centers));
for f_im_index = 1:length(f_im_bin_centers)
    
    fprintf("fim: %04d/%04d\n", f_im_index, length(f_im_bin_centers));

    tissue_params_adjusted = tissue_params;
    tissue_params_adjusted.f_im = f_im_bin_centers(f_im_index);

    % run simulations
    signal_per_r(f_im_index,:,:) = simulate_signals_single_axon( ...
        sim_params.r_bin_centers, ...
        mr_protocol, ...
        tissue_params_adjusted, ...
        "signal_approximation", "matrix");
end

r_bin_centers = sim_params.r_bin_centers;
r_bin_edges = sim_params.r_bin_edges;

save(fullfile(getenv("MRV_DATA_PATH"),...
    "simulations/signal_per_radius_ex_vivo_experimental_var_immobile_water.mat"), ...
    "signal_per_r", ...
    "r_bin_centers", ...
    "r_bin_edges", ...
    "sim_params", ...
    "f_im_bin_centers", ...
    "f_im_bin_edges", ...
    "tissue_params", ...
    "mr_protocol");
