% ========================================================================
% Illustrate effect of smoothing on in-vivo effective radii.
%
% Plots visual comparison of single subject effective radius map in native
% space before and after smoothing. Plots correlations of group-average
% effective radii against histological values before and after smoothing.
% ========================================================================

%% set up
roi_info_table = readtable(fullfile(getenv("MRV_DATA_PATH"), ...
    "histology/rawdata/roiinfo.tsv"), ...
    "FileType", "text", ...
    "Delimiter", "\t", ...
    "TextType", "string");
sim_params = get_default_simulation_parameters();
cc_eval_params = jsondecode(fileread(...
    "../../../parameters/cc_evaluation_parameters.json"));

%% in-vivo dMRI simulations
% load parameters and signal LUT for in-vivo simulations
mr_protocol_in_vivo = MrProtocol.fromJsonFile(...
    "../../../parameters/mr_protocol_in_vivo_experimental.json");
tissue_params_in_vivo = jsondecode(fileread( ...
    "../../../parameters/tissue_params_in_vivo.json"));

% get in-vivo-like axon radius distributions and r_eff
[r_roi_counts_in_vivo, r_eff_reference_in_vivo] = get_histology_data(...
    fullfile(getenv("MRV_DATA_PATH")), ...
    sim_params.r_bin_edges, ...
    sim_params.radius_approximation, ...
    "scaling_factor", tissue_params_in_vivo.histology_scaling_factor);


%% in-vivo dMRI experiments
% compute r_eff for experimental data
processed_data_dir = fullfile(getenv("MRV_DATA_PATH"), ...
    "mri_in_vivo/processed");
processed_subj_dir_fstructs = dir(fullfile(processed_data_dir, "sub*"));

subject_id_first = sscanf(processed_subj_dir_fstructs(1).name, 'sub-%s');
r_eff_image_example = niftiread(fullfile(processed_data_dir, ...
    sprintf("sub-%s/dwi/sub-%s_effectiveRadius.nii.gz", ...
    subject_id_first, subject_id_first)));

r_eff_mri_values = cell(height(roi_info_table), 1);
r_eff_mri_mean_values_per_subject = ...
    zeros(height(roi_info_table), length(processed_subj_dir_fstructs));
r_eff_mri_values_per_sub_smoothed = ...
    zeros(height(roi_info_table), length(processed_subj_dir_fstructs));
r_eff_mri_values_per_sub_unsmoothed = ...
    zeros(height(roi_info_table), length(processed_subj_dir_fstructs));

r_eff_images_unsmoothed = ...
    nan([length(processed_subj_dir_fstructs), size(r_eff_image_example)]);
r_eff_images_smoothed = ...
    nan([length(processed_subj_dir_fstructs), size(r_eff_image_example)]);

for subject_id_index = 1:length(processed_subj_dir_fstructs)
    subject_id = sscanf( ...
        processed_subj_dir_fstructs(subject_id_index).name, 'sub-%s');

    % read images
    r_eff_image_unsmoothed_file = fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_effectiveRadius.nii.gz", ...
        subject_id, subject_id));
    r_eff_image_unsmoothed = niftiread(r_eff_image_unsmoothed_file);
    r_eff_image_smoothed_file = fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/" + ...
        "sub-%s_roi-cc_desc-smoothed_effectiveRadius.nii.gz", ...
        subject_id, subject_id));
    r_eff_image_smoothed = niftiread(r_eff_image_smoothed_file);
    fa_image = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_FA.nii.gz", ...
        subject_id, subject_id)));
    cc_atlas_mask = niftiread(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/" + ...
        "sub-%s_label-ccMid_mask.nii.gz", ...
        subject_id, subject_id)));

    % exclude values outside corpus callosum (smoothed image)
    cc_mask_smoothed = cc_atlas_mask > 0 ...
        & fa_image >= cc_eval_params.fa_min ...
        & r_eff_image_smoothed >= cc_eval_params.r_eff_min;
    r_eff_image_smoothed(~cc_mask_smoothed) = nan;
    r_eff_images_smoothed(subject_id_index, :, :, :) = ...
        r_eff_image_smoothed;

    % exclude values outside corpus callosum (unsmoothed image)
    cc_mask_unsmoothed = cc_atlas_mask > 0 ...
        & fa_image >= cc_eval_params.fa_min ...
        & r_eff_image_unsmoothed >= cc_eval_params.r_eff_min;
    r_eff_image_unsmoothed(~cc_mask_unsmoothed) = nan;
    r_eff_images_unsmoothed(subject_id_index, :, :, :) = ...
        r_eff_image_unsmoothed;

    % extract values at ROI coordinates
    loc_table = readtable(fullfile(processed_data_dir, ...
        sprintf("sub-%s/dwi/sub-%s_roiinfo.tsv", ...
        subject_id, subject_id)), ...
        "FileType", "text", ...
        "Delimiter", "\t");
    sub_table = loc_table(:, ...
        ["native_voxel_x", "native_voxel_y", "native_voxel_z"]);  
    loc_voxels = int16(round(sub_table.Variables)+1);
    for roi_index = 1:length(r_eff_mri_values)
        x = loc_voxels(roi_index,1);
        y = loc_voxels(roi_index,2);
        z = loc_voxels(roi_index,3);
        r_eff_mri_values_per_sub_smoothed(roi_index, subject_id_index) = ...
            r_eff_image_smoothed(x, y, z);
        r_eff_mri_values_per_sub_unsmoothed(roi_index, subject_id_index) = ...
            r_eff_image_unsmoothed(x, y, z);
    end
end

valid_idx = sum(~isnan(r_eff_mri_values_per_sub_smoothed),2)>=3;
r_eff_mri_mean_values_smoothed = ...
    mean(r_eff_mri_values_per_sub_smoothed, 2, 'omitnan');
r_eff_mri_mean_values_smoothed(~valid_idx) = nan;

valid_idx = sum(~isnan(r_eff_mri_values_per_sub_unsmoothed),2)>=3;
r_eff_mri_mean_values_unsmoothed = ...
    mean(r_eff_mri_values_per_sub_unsmoothed, 2, 'omitnan');
r_eff_mri_mean_values_unsmoothed(~valid_idx) = nan;

%% plots
% set up figure
color_order = get_default_color_order();
color_ex_vivo = color_order(2,:);
color_in_vivo = color_order(1,:);
lims = [0 4];
clims = [2 3.5];
subject_example_index = 1;
x_plot_idx = 44;
y_plot_idx = 23:57;
z_plot_idx = 22:35;

% set up 
fig_handle  = figure;
set(fig_handle, get_default_figure_settings());
set(gcf, 'units', 'centimeters', ...
    'position', [0, 0, 12.1, 5.5]);
layout_patterns = tiledlayout(1, 2, ...
    "TileSpacing", "none", ...
    "Padding", "tight");

% unsmoothed corpus callosum pattern
nexttile(layout_patterns);
hold on;
title("No smoothing", ...
    'interpreter', 'latex');
r_eff_map = squeeze(r_eff_images_unsmoothed( ...
    subject_example_index, x_plot_idx, y_plot_idx, z_plot_idx))';
r_eff_map = fliplr(r_eff_map);
h = imagesc(r_eff_map);
axis image;
axis off;
set(h, 'AlphaData', ~isnan(r_eff_map));
clim(clims);

% smoothed corpus callosum pattern
nexttile(layout_patterns);
hold on;
title("Smoothed" + newline + "(FWHM = 3.75 mm)", ...
    'interpreter', 'latex');
r_eff_map = squeeze(r_eff_images_smoothed( ...
    subject_example_index, x_plot_idx, y_plot_idx, z_plot_idx))';
r_eff_map = fliplr(r_eff_map);
h = imagesc(r_eff_map);
axis image;
axis off;
set(h, 'AlphaData', ~isnan(r_eff_map) & r_eff_map > 0);
clim(clims);

% add colorbar
% ax = nexttile(t);
cb = colorbar();
cb.Location = "northoutside";
clim(clims);  % Set color limits based on 'clims'
cb.Label.Interpreter = "latex";
cb.Label.String = "$r_{\mathrm{eff}}$ [$\mu$m]";
cb.Label.FontSize = 10;
cb.Layout.Tile = 'north'; % Position colorbar in the top region

% save_figure
print(gcf, '-dsvg', "smoothing_pattern.svg");

fig_handle  = figure;
set(fig_handle, get_default_figure_settings());
layout_correlation = tiledlayout(1, 2, ...
    "TileSpacing", "tight", ...
    "Padding", "tight");
set(gcf, 'units', 'centimeters', ...
    'position', [0, 0, 12.1, 8]);

% correlation plot for unsmoothed data
ax = nexttile(layout_correlation);
rand_stream = RandStream(sim_params.random_generator, ...
    'Seed', sim_params.random_seed);
plot_r_eff_correlation_ensemble(ax, ...
    r_eff_reference_in_vivo, ...
    r_eff_mri_mean_values_unsmoothed, ...
    'color', color_in_vivo, ...
    'xlim', lims, ...
    'ylim', lims, ...
    'rand_stream', rand_stream);
xlabel('$r_{\mathrm{eff}}$ [$\mu$m] (histology)', ...
    'Interpreter', 'latex');
ylabel("$r_{\mathrm{eff}}$ [$\mu$m]" + newline ...
    + "(dMRI experiments)", ...
    'Interpreter', 'latex');
lgd = legend('Interpreter', 'latex', ...
    'Location', 'northoutside', ...
    'FontSize', 7);
lgd.ItemTokenSize(1) = 15;

% correlation plot for smoothed data
ax = nexttile(layout_correlation);
rand_stream = RandStream(sim_params.random_generator, ...
    'Seed', sim_params.random_seed);
plot_r_eff_correlation_ensemble(ax, ...
    r_eff_reference_in_vivo, ...
    r_eff_mri_mean_values_smoothed, ...
    'color', color_in_vivo, ...
    'xlim', lims, ...
    'ylim', lims, ...
    'rand_stream', rand_stream);
xlabel('$r_{\mathrm{eff}}$ [$\mu$m] (histology)', ...
    'Interpreter', 'latex');
ylabel("$r_{\mathrm{eff}}$ [$\mu$m] (dMRI experiments)", ...
    'Interpreter', 'latex');
lgd = legend('Interpreter', 'latex', ...
    'Location', 'northoutside', ...
    'FontSize', 7);
lgd.ItemTokenSize(1) = 15;

% save_figure
print(gcf, '-dsvg', "smoothing_correlation.svg");